#%RAML 1.0
---
title: Hello World
version: 1.0

protocols: [ HTTPS ]
baseUri: https://helloworld.service.hmrc.gov.uk/
securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    settings:
      authorizationUri: https://api.service.hmrc.gov.uk/oauth/authorize
      accessTokenUri: https://api.service.hmrc.gov.uk/oauth/token
      authorizationGrants: [ authorization_code, client_credentials ]
      scopes:

annotationTypes:
  scope:
  throttlingTier:

mediaType: application/hal+json

/test:
  /hello:
    get:
      displayName: Say Hello
      description: |
        A simple hello api
      (scope): "read:hello"
      (throttlingTier): LOW
      securedBy: [ oauth_2_0: { scopes: [ "read:hello" ] } ]


      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message" : "Hello World"
                }
