#%RAML 1.0
---
title: Hello World
version: 1.0

protocols: [ HTTPS ]
baseUri: https://helloworld.service.hmrc.gov.uk/
securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    settings:
      authorizationUri: https://api.service.hmrc.gov.uk/oauth/authorize
      accessTokenUri: https://api.service.hmrc.gov.uk/oauth/token
      authorizationGrants: [ authorization_code, client_credentials ]
      scopes:

uses:
  annotations: annotation-lib.raml

mediaType: application/hal+json

/test:
  /hello:
    get:
      displayName: Say Hello
      description: |
        A simple hello api
      (annotations.scope): "read:hello"
      securedBy: [ oauth_2_0: { scopes: [ "read:hello" ] } ]
