#%RAML 1.0
---
title: Hello World
version: 1.0

protocols: [ HTTPS ]
baseUri: https://helloworld.service.hmrc.gov.uk/

mediaType: application/hal+json

/test:
  /hello:
    get:
      displayName: Say Hello
      description: |
        A simple hello api

      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message" : "Hello World"
                }
